#!/usr/bin/env python3
"""
Build Branchly as a single executable file.

One command, the same on every platform. Run it on the system the file is meant
for, because PyInstaller cannot build for another one:

    ./build-exe.py          Linux   -> dist/branchly-linux-x86_64-<version>-build<build>
    py build-exe.py         Windows -> dist/branchly-windows-x86_64-<version>-build<build>.exe

What it does:

1. writes the VERSION file from the commit history, which the executable
   carries instead of a history of its own,
2. creates a private build environment in ``build/exe/venv``, without the
   system's packages, so nothing the build machine happens to have ends up in
   the file,
3. installs PyInstaller and the pinned packages from ``requirements.txt``,
4. stages the read-only files the program reads at run time (translations,
   icons, the askpass helper, the manuals with their pictures, VERSION) in the
   layout a checkout has,
5. runs PyInstaller and checks that the result starts.

Git is not part of the file: Branchly drives the system's git, as it does from
a checkout. tkinter and the installer window are left out, because the
executable has nothing to install.

Options:

    --clean     rebuild the build environment from scratch
    --keep-env  reuse the build environment without updating its packages
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import venv
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import install_dependencies  # noqa: E402
import paths  # noqa: E402
import version  # noqa: E402
from constants import APP_NAME  # noqa: E402

BUILD_DIR = ROOT / "build" / "exe"
VENV_DIR = BUILD_DIR / "venv"
STAGE_DIR = BUILD_DIR / "stage"
WORK_DIR = BUILD_DIR / "work"
SPEC_FILE = WORK_DIR / "branchly.spec"
DIST_DIR = ROOT / "dist"

# The same as Branchly itself; the build environment is made from this interpreter.
MINIMUM_PYTHON = (3, 11)

# Needs 6.9 or newer for PYINSTALLER_RESET_ENVIRONMENT, which the updater sets so
# a restarted executable unpacks itself afresh.
PYINSTALLER_SPEC = "pyinstaller>=6.9"

# Branchly's own packages. Most are imported at the top of a module and found by
# PyInstaller anyway; a few only inside a function, which this makes certain.
OWN_PACKAGES = ["config", "github_api", "gitops", "models", "services", "ui"]

# keyring finds its backends through entry points, which PyInstaller cannot see:
# the backends, their helpers and keyring's metadata go in explicitly.
KEYRING_PACKAGES = ["keyring.backends"]
KEYRING_PACKAGES_LINUX = ["secretstorage", "jeepney"]
KEYRING_PACKAGES_WINDOWS = ["win32ctypes"]
METADATA_PACKAGES = ["keyring"]

# Modules that must never end up in the executable: the Tk installer window and
# its toolkit. The executable carries its packages and has nothing to install.
EXCLUDED_MODULES = ["tkinter", "_tkinter", "installer_ui"]

# Read-only files the program opens at run time, relative to the project root.
DATA_PATTERNS = (
    "VERSION",
    "locales/*.json",
    "resources/*",
    "docs/MANUAL.*.md",
    "docs/screenshots/**/*.png",
)

SPEC_TEMPLATE = '''# Generated by build-exe.py - edit that script, not this file.
from PyInstaller.utils.hooks import collect_submodules, copy_metadata

datas = {datas!r}
hiddenimports = {hidden!r}
for package in {submodules!r}:
    hiddenimports += collect_submodules(package)
for package in {metadata!r}:
    datas += copy_metadata(package)

a = Analysis(
    [{entry!r}],
    pathex=[{root!r}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={excludes!r},
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={name!r},
    debug=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    # No console window on Windows; Branchly is a window of its own.
    console=False,
    icon={icon!r},
)
'''


def info(message: str) -> None:
    """
    Prints a progress line.

    Args:
        message: The line.

    Returns:
        None
    """

    print("[build-exe] " + message, flush=True)


def fail(message: str) -> None:
    """
    Prints an error and stops with exit code 1.

    Args:
        message: What went wrong.

    Returns:
        None
    """

    print("[build-exe] ERROR: " + message, file=sys.stderr, flush=True)
    sys.exit(1)


def venv_python() -> Path:
    """
    Returns the interpreter of the build environment.

    Returns:
        Path: ``python`` inside ``build/exe/venv``.
    """

    if paths.is_windows():
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def run(command: list[object], **kwargs: object) -> None:
    """
    Runs a command and stops the build when it fails.

    Args:
        command: Program and arguments.
        **kwargs: Passed on to ``subprocess.run``.

    Returns:
        None
    """

    info("$ " + " ".join(str(part) for part in command))
    completed = subprocess.run([str(part) for part in command], check=False, **kwargs)  # noqa: S603
    if completed.returncode != 0:
        fail(f"command failed with exit code {completed.returncode}")


def check_build_host() -> None:
    """
    Stops early when this machine cannot produce a complete program.

    Returns:
        None
    """

    if sys.version_info[:2] < MINIMUM_PYTHON:
        needed = ".".join(str(part) for part in MINIMUM_PYTHON)
        fail(f"building needs Python {needed} or newer, the same as Branchly itself.")
    if shutil.which("git") is None:
        fail("git is missing - the version number is read from the commit history.")


def write_version() -> version.Version:
    """
    Writes the VERSION file from the history and returns what it says.

    The executable has no history of its own, so this file is the only place its
    version can come from.

    Returns:
        version.Version: The version the build carries.
    """

    written = version.write_file(ROOT)
    if written is None:
        fail("no commit history to number this build with (a shallow clone? fetch-depth: 0).")
    version.forget()
    return version.current()


def bundled_packages() -> list[str]:
    """
    Returns the pip packages to install into the build environment.

    Returns:
        list[str]: PyInstaller and every pin from ``requirements.txt``.
    """

    pins = install_dependencies.parse_pinned_requirements(ROOT / "requirements.txt")
    return [PYINSTALLER_SPEC] + [f"{pin.name}=={pin.version}" for pin in pins]


def prepare_venv(clean: bool, keep: bool) -> None:
    """
    Creates or refreshes the build environment.

    It is created without the system packages, so nothing the build machine
    happens to have installed ends up in the executable.

    Args:
        clean: Remove an existing environment first.
        keep: Reuse an existing environment without updating it.

    Returns:
        None
    """

    if clean and VENV_DIR.exists():
        info("Removing the old build environment ...")
        shutil.rmtree(VENV_DIR)
    if not venv_python().exists():
        info(f"Creating the build environment in {VENV_DIR} ...")
        venv.EnvBuilder(with_pip=True).create(str(VENV_DIR))
    elif keep:
        info("Reusing the build environment as it is.")
        return
    pip = [venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check"]
    run([*pip, "pip"])
    run([*pip, *bundled_packages()])


def data_files() -> list[Path]:
    """
    Returns the read-only files the executable carries, relative to the root.

    Returns:
        list[Path]: Every file matched by :data:`DATA_PATTERNS`.
    """

    found: set[Path] = set()
    for pattern in DATA_PATTERNS:
        found.update(item.relative_to(ROOT) for item in ROOT.glob(pattern) if item.is_file())
    return sorted(found)


def stage_data() -> Path:
    """
    Copies the read-only files into the layout a checkout has.

    The executable unpacks them to ``sys._MEIPASS``, which ``paths.project_root``
    returns there, so every path the program builds stays the same.

    Returns:
        Path: The staged directory.
    """

    if STAGE_DIR.exists():
        shutil.rmtree(STAGE_DIR)
    members = data_files()
    for relative in members:
        destination = STAGE_DIR / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / relative, destination)
    info(f"Staged {len(members)} data files.")
    return STAGE_DIR


def hidden_packages() -> list[str]:
    """
    Returns the packages whose every submodule goes into the executable.

    Returns:
        list[str]: Branchly's own packages and keyring's backends for this platform.
    """

    packages = OWN_PACKAGES + KEYRING_PACKAGES
    if paths.is_linux():
        packages += KEYRING_PACKAGES_LINUX
    elif paths.is_windows():
        packages += KEYRING_PACKAGES_WINDOWS
    return packages


def spec_text(staged: Path) -> str:
    """
    Returns the PyInstaller spec file for this platform.

    Args:
        staged: The staged data directory from :func:`stage_data`.

    Returns:
        str: The content of the spec file.
    """

    name = paths.executable_name()
    if name.endswith(".exe"):
        name = name[: -len(".exe")]
    icon = ROOT / "resources" / "branchly.ico"
    return SPEC_TEMPLATE.format(
        datas=[(str(staged), ".")],
        hidden=[],
        submodules=hidden_packages(),
        metadata=METADATA_PACKAGES,
        entry=str(ROOT / "run.py"),
        root=str(ROOT),
        excludes=EXCLUDED_MODULES,
        name=name,
        icon=str(icon) if paths.is_windows() and icon.is_file() else None,
    )


def smoke_test(executable: Path, expected: str) -> None:
    """
    Starts the result once and makes sure it answers.

    Args:
        executable: The built file.
        expected: The version number its output must contain.

    Returns:
        None
    """

    info(f"Starting {executable.name} --version ...")
    completed = subprocess.run(  # noqa: S603 - the file this script just built
        [str(executable), "--version"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=300,
        check=False,
    )
    output = completed.stdout.decode("utf-8", errors="replace").strip()
    if completed.returncode != 0:
        fail(f"the executable did not start (exit code {completed.returncode}):\n{output}")
    # A windowed Windows build has no stdout to print to; the exit code has to do.
    if output and expected not in output:
        fail(f"the executable reports {output!r}, expected {expected}")
    info("OK: " + (output or "exit code 0"))


def main() -> int:
    """
    Runs the whole build.

    Returns:
        int: Process exit code.
    """

    parser = argparse.ArgumentParser(description=f"Build {APP_NAME} as a single executable file.")
    parser.add_argument("--clean", action="store_true", help="rebuild the build environment from scratch")
    parser.add_argument(
        "--keep-env", action="store_true", help="reuse the build environment without updating its packages"
    )
    args = parser.parse_args()

    check_build_host()
    current = write_version()
    info(f"{APP_NAME} {current.label} for {paths.executable_name()}")
    prepare_venv(clean=args.clean, keep=args.keep_env)
    staged = stage_data()
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_FILE.write_text(spec_text(staged), encoding="utf-8")
    run(
        [venv_python(), "-m", "PyInstaller", "--noconfirm", "--clean",
         "--distpath", DIST_DIR, "--workpath", WORK_DIR, SPEC_FILE],
        cwd=str(ROOT),
    )

    result = DIST_DIR / paths.executable_name()
    if not result.is_file():
        fail(f"PyInstaller finished but {result} is missing")
    smoke_test(result, current.name)
    info(f"Done: {result} ({result.stat().st_size / 1048576:.1f} MB)")
    system = "Windows" if paths.is_windows() else ("macOS" if paths.is_macos() else "Linux")
    info(f"This file runs on {system} only; build on the other system for its own file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
